# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fbc36a411d43cdaf1a76ecb7beffccdc"
name = "Pen and Paper"
handle = "pen-and-paper"
application_url = "https://6387-94-114-245-47.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_orders,read_customers,read_fulfillments,write_script_tags"

[auth]
redirect_urls = [ "https://6387-94-114-245-47.ngrok-free.app/auth/callback" ]

[pos]
embedded = false
